### ISSUE TITLE
ValueError statt IndexError

### ISSUE THREAD

**Issue by HealingArcYT** [Paul-Lukas/pytrix#6]
Sollte der ValueError in src.config.Config nicht eigentlich ein IndexError sein?

Also so:
```py
def __getitem__(self, item):
    if len(item) != 2:
        raise IndexError('Index needs two values example: [1, 2]')
    return self.matrix[item[0]][item[1]]

def __setitem__(self, key, value):
    if len(key) != 2:
        raise IndexError('Index needs two values example: [1, 2]')
    self.matrix[key[0]][key[1]] = value
```

**Comment by Paul-Lukas** [comment]
Ist der Ausschnitt aus src.output.matrix.py gemeint?
Hier trifft der ValueError zu, da ein falscher Wert übergeben wurde (ein Tupel mit nur einem Wert, statt den erwarteten zwei). 
Der IndexError würde ohne die If-Abfrage auftreten, wenn ein falscher Index aufgerufen wird.

**Comment by HealingArcYT** [comment]
In der __getitem__ Methode, da schreibst du ja auch rein, dass der Index aus zwei Werten bestehen muss, also sollte das meiner Meinung nach ein IndexError sein
